### ISSUE TITLE
Can not work with IDA v7.0

### ISSUE THREAD

**Issue by dsanke** [yeggor/UEFI_RETool#8]
Failed while executing plugin_t.run():
Traceback (most recent call last):
  File "C:/Program Files/IDA_Pro_v7.0/plugins/uefi_analyser.py", line 52, in run
    self._analyse_all()
  File "C:/Program Files/IDA_Pro_v7.0/plugins/uefi_analyser.py", line 93, in _analyse_all
    prot_explorer.run()
  File "C:/Program Files/IDA_Pro_v7.0/plugins\uefi_analyser\prot_explorer.py", line 181, in run
    analyser.analyse_all()
  File "C:/Program Files/IDA_Pro_v7.0/plugins\uefi_analyser\analyser.py", line 438, in analyse_all
    self.make_comments()
  File "C:/Program Files/IDA_Pro_v7.0/plugins\uefi_analyser\analyser.py", line 307, in make_comments
    idc.op_stroff(address, 0, EFI_BOOT_SERVICES_ID, 0)
  File "C:\Program Files\IDA_Pro_v7.0\python\idc.py", line 1267, in op_stroff
    return ida_bytes.op_stroff(ea, n, path.cast(), 1, delta)
  File "C:\Program Files\IDA_Pro_v7.0\python\ida_bytes.py", line 1007, in op_stroff
    return _ida_bytes.op_stroff(*args)
TypeError: in method 'op_stroff', argument 1 of type 'insn_t const &'

**Comment by yeggor** [comment]
Currently, the plugin only works correctly with IDA 7.4 and python 3.
You can use an [older version of the plugin](https://github.com/yeggor/UEFI_RETool/tree/64f82e2456fc93510dd7b86675ae50825c9037d0/ida_plugin) to work with ida 7.0 and python 2 (some new features are missing here).

**Comment by dsanke** [comment]
Thanks for the reply! I'll try older version.
